(when (configuration-layer/package-usedp 'projectile)

  (defun jpstone/npm-run-dev ()
    (interactive)
    (projectile-run-compilation "npm run dev"))
  (defun jpstone/npm-run-prod ()
    (interactive)
    (projectile-run-compilation "npm run prod"))
  (defun jpstone/npm-run-test ()
    (interactive)
    (projectile-run-compilation "npm run test"))
  (defun jpstone/npm-run-build ()
    (interactive)
    (projectile-run-compilation "npm run build")))
